### ISSUE TITLE
need help build

### ISSUE THREAD

**Issue by lotey** [Xu-Mj/sandcat#5]
after see the document，I use ubuntu 20.04 build failed，error info below
![image](https://github.com/Xu-Mj/sandcat/assets/19348658/bc6447ff-e6d0-4406-9bae-6d028ce5b708)
please help
thanks

**Comment by Xu-Mj** [comment]
> after see the document，I use ubuntu 20.04 build failed，error info below
> 
> ![image](https://github.com/Xu-Mj/sandcat/assets/19348658/bc6447ff-e6d0-4406-9bae-6d028ce5b708)
> 
> please help
> 
> thanks
is there any gui on your ubuntu? if not, please use `trunk serve`.

**Comment by Xu-Mj** [comment]
> after see the document，I use ubuntu 20.04 build failed，error info below ![image](https://private-user-images.githubusercontent.com/19348658/326240995-bc6447ff-e6d0-4406-9bae-6d028ce5b708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTI5MDEsIm5iZiI6MTcxNDI5MjYwMSwicGF0aCI6Ii8xOTM0ODY1OC8zMjYyNDA5OTUtYmM2NDQ3ZmYtZTZkMC00NDA2LTliYWUtNmQwMjhjZTViNzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA4MjMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MGJkM2QyMDc5Y2YxNmJlNmExOTljNDdiNmM0NjFkMDQwMmNhMmQ0YjJhNWU1YzRlODU5OWRhYTE1ZWQxNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lrRtI5kdTNBS-cFQPJqOevzP5DVqevYbLgeXeYHV4eM) please help thanks

execute command `rustup target add wasm32-unknown-unknown` and run cargo tauri dev again. is there any GUI on you ubuntu ? by the way. if not, please use the `trunk serve`

**Comment by lotey** [comment]
my ubuntu no GUI and now I build sandcat success,but sandcat-backend failed,like below
![image](https://github.com/Xu-Mj/sandcat/assets/19348658/d71f2a8b-ce06-4279-b0c1-21ced0c5d429)
and I want know,after build success,how can I deploy to centos7 server

**Comment by lotey** [comment]
![image](https://github.com/Xu-Mj/sandcat/assets/19348658/75791f14-38cd-4435-a358-16b553804c15)

**Comment by Xu-Mj** [comment]
> ![image](https://github.com/Xu-Mj/sandcat/assets/19348658/75791f14-38cd-4435-a358-16b553804c15)
> 
> 

the backend side deployment doc is on the way. I'm working on it.

**Comment by lotey** [comment]
ok,thanks

**Comment by Xu-Mj** [comment]
Hi, I've included the documentation [here](https://github.com/Xu-Mj/sandcat-backend?tab=readme-ov-file#development), which you can review at your convenience. should you come acrose any errors. please respond in this thread.

**Comment by Xu-Mj** [comment]
Remember to update the git repository. 
```shell
git pull
```

**Comment by lotey** [comment]
build failed,see below
![image](https://github.com/Xu-Mj/sandcat/assets/19348658/16248f90-cde0-43e8-9a29-378ee27ed8fd)

**Comment by Xu-Mj** [comment]
update your local repository,`git pull` and rebuild again

**Comment by lotey** [comment]
staill failed,like rdkafka dependency failed,already install librdkafka-dev and execute 2 dynamic-linking,see below
![image](https://github.com/Xu-Mj/sandcat/assets/19348658/9a09628d-0db5-4fbd-899d-2162070bd116)

**Comment by lotey** [comment]
or can you make a docker images,and expose config item

**Comment by Xu-Mj** [comment]
The issue you've encountered stems from `rdkafka` utilizing dynamic linking to `librdkafka`. To simplify the process for you, I've switched it to use `cmake-build`. 

So please ensure that the `rdkafka` dependency is set to `rdkafka = { version = "0.36.2", features = ["cmake-build"] }` in the following files: `consumer/Cargo.toml` and `chat/Cargo.toml`

**Comment by Xu-Mj** [comment]
> or can you make a docker images,and expose config item

this project frequently undergoes updates. continually updating the Docker image with every project change could become quite time-consuming. I'll crate a Docker image once the project reaches a stable phase.

**Comment by lotey** [comment]
![image](https://github.com/Xu-Mj/sandcat/assets/19348658/7dd43642-6051-4f4a-9590-48f0ce33f795)

**Comment by Xu-Mj** [comment]
in your situation, you just need to update your local repository and install `librdkafka`, there is no need to run `cargo add rdkafka --features dynamic-linking -p consumer
cargo add rdkafka --features dynamic-linking -p chat` as those command are specific to the Windows platform.

remove the 'dynamic-linking' feature from `rdkafka` and rebuild again.

**Comment by lotey** [comment]
very thank,I've success
![image](https://github.com/Xu-Mj/sandcat/assets/19348658/d3049d25-a01e-4535-99e1-476868d97afe)
